#FROM maven:latest AS mainmaven
#COPY lib webapp
#COPY src webapp
#COPY pom.xml webapp
#RUN cd webapp && mvn clean install
#RUN cp webapp/target/webapp.war /shared
#RUN cd && ls
#RUN cd /webapp/target/ && ls
#EXPOSE 5555

